version: '3'
services:
  python:
    restart: always
    build:
      context: .
      dockerfile: ./Python/Dockerfile
    container_name: 'python'
    working_dir: '/code'
    tty: true
    volumes:
      - ./Python:/code